export const TARGET_WPM = 100;
export const TARGET_ACCURACY = 95;
export const HIGH_FREQ_BIAS = 0.75; // % chance of getting a high frequency gram
export const HIGH_FREQ_CUTTOFF = 0.35; // % of grams considered high frequency
export const HISTORY_BIAS = 0.75; // % of words that consider your history
export const HISTORY_SPREAD = 5; // top x historical scores to consider
export const SCORE_LIFESPAN = 10; // number of sprints before evaluating next problem set
export const IDLE_THRESHOLD = 5000; // millis of idle to ignore results
export const NGRAM_COMPONENT = 0.5; // ngram should be at least this % of a word
export const MAX_SPRINT_LENGTH = 35; // max characters our sprints can ever be
export const START_SPRINT_LENGTH = 20; // starting characters for a sprint
